//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempFoodHandlingCertificates2014.Models
{
    using System;
    
    public partial class ApplicantDetails
    {
        public string ApplicantName { get; set; }
        public string ApplicantPhoneNumber { get; set; }
        public string ApplicantEmail { get; set; }
        public string ApplicantPostalAddress { get; set; }
    }
}
