//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempFoodHandlingCertificates2014.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.EventDetails = new EventDetails();
            this.StallDetails = new StallDetails();
            this.ApplicantDetails = new ApplicantDetails();
            this.FoodDetails = new FoodDetails();
        }
    
        public int Id { get; set; }
        public Nullable<int> AppID { get; set; }
        public string GUID { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string StallType { get; set; }
        public string HowFoodsKeptCold { get; set; }
        public string HowFoodsKeptHot { get; set; }
        public string HandwashFacilities { get; set; }
    
        public EventDetails EventDetails { get; set; }
        public StallDetails StallDetails { get; set; }
        public ApplicantDetails ApplicantDetails { get; set; }
        public FoodDetails FoodDetails { get; set; }
    
        public virtual FoodEvent FoodEvent { get; set; }
        public virtual ProcessApplication ProcessApplication { get; set; }
    }
}
