//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempFoodHandlingCertificates2014.Models
{
    using System;
    
    public partial class EventDetails
    {
        public string EventName { get; set; }
        public string EventLocation { get; set; }
        public string EventDescription { get; set; }
        public Nullable<System.DateTime> EventStartDate { get; set; }
        public string OtherEventDates { get; set; }
    }
}
