//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempFoodHandlingCertificates2014.Models
{
    using System;
    
    public partial class FoodDetails
    {
        public string FoodDetailsTypeOfFood { get; set; }
        public string FoodDetailsWhereStoredPrior { get; set; }
        public string FoodDetailsFoodsPreparedOffSite { get; set; }
        public string FoodDetailsFoodsPreparedOnSite { get; set; }
    }
}
